# Generated by Django 4.2.6 on 2024-06-08 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='otp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Payment.otp'),
        ),
    ]
