# Generated by Django 4.2.6 on 2024-06-08 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_payment_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('one', 'One')], default='one', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='otp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Payment.otp'),
        ),
    ]
