# Generated by Django 4.2.6 on 2024-06-05 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_subscription_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid_exam',
        ),
    ]
