# Generated by Django 5.0.6 on 2024-06-23 17:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Announcement Category',
                'verbose_name_plural': 'Announcement Categories',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='Announcements/thumbnails')),
                ('description', models.TextField()),
                ('application_link', models.URLField(max_length=255, null=True)),
                ('announcer', models.CharField(max_length=255)),
                ('announcer_description', models.TextField(null=True)),
                ('announcer_logo', models.ImageField(null=True, upload_to='Announcements/announcer_logos')),
                ('valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Announcement.announcementcategory')),
            ],
        ),
    ]
