# Generated by Django 5.0.6 on 2024-06-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcer_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='Announcements/announcer_logos'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='application_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
