# Generated by Django 5.0.6 on 2024-06-24 06:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Announcement', '0002_alter_announcement_announcer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcer_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
