# Generated by Django 4.2.6 on 2024-06-02 10:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0872dba2-6d2b-4fb3-8dd9-64828583ab31'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('46e6884f-d530-4ad7-9662-837b87a25a7f'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('number_of_questions', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=1, verbose_name='Duration of Quiz')),
                ('required_score_to_pass', models.IntegerField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.faculties')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('68026c0d-39ca-4160-869b-2d43886911aa'), editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ec879054-6ab4-4dc2-ade1-935447ffda9d'), editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('correct', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.quiz')),
            ],
        ),
    ]
