# Generated by Django 4.2.6 on 2024-06-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_alter_answer_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='quiz',
            new_name='question',
        ),
    ]
