# Generated by Django 4.2.6 on 2024-06-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_rename_quiz_answer_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculties',
            options={'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
    ]
