# Generated by Django 4.2.6 on 2024-06-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_alter_faculties_options_alter_quiz_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculties',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='faculties',
            name='thumbnail',
            field=models.ImageField(default=None, null=True, upload_to='faculty'),
        ),
    ]
