# Generated by Django 4.2.6 on 2024-06-04 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_usersubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
