# Generated by Django 4.2.6 on 2024-06-04 12:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_alter_usersubmission_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='quiz',
            field=models.ForeignKey(default='4234cc64-3d93-45ae-9790-6ef8090b6532', on_delete=django.db.models.deletion.CASCADE, to='Quiz.quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
