# Generated by Django 5.0.6 on 2024-06-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESOKO', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_category',
            options={'verbose_name_plural': 'Product Categories'},
        ),
    ]
