# Generated by Django 5.0.6 on 2024-06-28 01:04

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESOKO', '0002_alter_product_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Esoko',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('product_price', models.IntegerField(blank=True, null=True)),
                ('thumbnail', models.ImageField(upload_to='products/thumbnails')),
                ('product_location', models.CharField(max_length=255)),
                ('owner_contact', models.CharField(max_length=40)),
                ('valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bought', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ESOKO.product_category')),
            ],
        ),
    ]
